services:
    phlexible_indexer_page_media.mapper:
        class: Phlexible\Bundle\IndexerPageMediaBundle\Indexer\DocumentMapper
        arguments:
            - @doctrine.dbal.default_connection
            - @event_dispatcher
            - @phlexible_media_manager.volume_manager
            - @phlexible_tree.tree_manager
            - @phlexible_media_manager.file_usage_manager
            - @phlexible_media_manager.folder_usage_manager
            - @doctrine.orm.entity_manager

    # event listeners
    phlexible_indexer_page_media.document_listener:
        class: Phlexible\Bundle\IndexerPageMediaBundle\EventListener\DocumentListener
        tags:
            - {name: kernel.event_subscriber}

    phlexible_indexer_page_media.node_listener:
        class: Phlexible\Bundle\IndexerPageMediaBundle\EventListener\NodeListener
        tags:
            - {name: kernel.event_subscriber}
