services:
    phlexible_indexer_page_media.page_to_media_mapper:
        class: Phlexible\Bundle\IndexerPageMediaBundle\Mapper\PageToMediaMapper
        arguments:
            - "@doctrine.dbal.default_connection"
            - "@event_dispatcher"
            - "@phlexible_media_manager.volume_manager"
            - "@phlexible_tree.tree_manager"
            - "@phlexible_media_manager.file_usage_manager"
            - "@phlexible_media_manager.folder_usage_manager"
            - "@phlexible_siteroot.siteroot_manager"
            - "@phlexible_indexer_storage_elastica.index"

    # event listeners
    phlexible_indexer_page_media.media_document_listener:
        class: Phlexible\Bundle\IndexerPageMediaBundle\EventListener\MediaDocumentListener
        arguments:
            - "@phlexible_indexer_page_media.page_to_media_mapper"
        tags:
            - {name: kernel.event_subscriber}

    phlexible_indexer_page_media.node_listener:
        class: Phlexible\Bundle\IndexerPageMediaBundle\EventListener\NodeListener
        arguments:
            - "@phlexible_queue.job_manager"
        tags:
            - {name: kernel.event_subscriber}
